import {
  BellRing,
  BriefcaseMedical,
  CalendarDays,
  CalendarPlus2,
  CalendarRange,
  ContactRound,
  Clock3,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  IdCard,
  LayoutDashboard,
  RotateCcw,
  ShieldCheck,
  SlidersHorizontal,
  UserRoundCog,
  UserSquare2,
  type LucideIcon,
} from 'lucide-react';

import type { NavigationIconKey } from '@/lib/module-navigation';

export const navigationIconMap: Record<NavigationIconKey, LucideIcon> = {
  admin: ShieldCheck,
  'medicina-laboral': BriefcaseMedical,
  dictamenes: ClipboardCheck,
  admisiones: UserSquare2,
  recomendaciones: ClipboardPlus,
  agenda: CalendarDays,
  dashboard: LayoutDashboard,
  employees: IdCard,
  profiles: UserRoundCog,
  reopen: RotateCcw,
  notifications: BellRing,
  audit: ClipboardList,
  'agenda-list': CalendarRange,
  'agenda-create': CalendarPlus2,
  'agenda-schedule': Clock3,
  'patient-reception': ContactRound,
  'reception-policies': SlidersHorizontal,
};
